# .streamlit/secrets.toml
# Add your actual API keys here (this file should not be committed to version control)

hf_token = "YOUR_HUGGING_FACE_TOKEN_HERE"

openweather_api_key = "YOUR_OPENWEATHER_API_KEY_HERE"

groq_api_key = "YOUR_GROQ_API_KEY_HERE"

openai_api_key = "YOUR_OPENAI_API_KEY_HERE"

